# Generated by Django 5.0.6 on 2026-04-22 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_injuryreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='discipline',
            field=models.CharField(default='Boxing', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='duration',
            field=models.IntegerField(help_text='minutes'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='intensity',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available', models.BooleanField(default=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.athlete')),
            ],
        ),
    ]
