# Generated by Django 5.0.6 on 2026-04-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trainingsession_discipline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='discipline',
            field=models.CharField(default='Boxing', max_length=100),
        ),
        migrations.DeleteModel(
            name='Injury',
        ),
    ]
