# Generated by Django 5.0.6 on 2026-04-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_trainingsession_discipline_delete_injury'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
